###########################################################
# ruff config
# weikang
# 2026-01-28
# doc: https://docs.astral.org.cn/ruff/rules
###########################################################

ignore = [
    "UP037",
    "B006",
    "D101",
    "D200",
    "D204",
    "D205",
    "D210",
    "D212",
    "D213",
    "D413",
    "D107",
    "N802",
    "TRY300",
    "ANN204",
    "S113",
    "F541",
    "F401",  # 禁用“未使用导入”规则
    "F841",  # 禁用“局部变量赋值未使用”规则
    "D100",  # 禁用“模块文档字符串格式”规则
    "D103",  # 禁用“函数文档字符串格式”规则
    "W293",  # 禁用空行规则
    "T201",  # 禁用“多行注释格式”规则
    "E501",  # 禁用行太长规则
    "E731",  # 禁用lambda赋值
    "RUF003",
    "ANN001",
    "ANN201",
    "ANN202",
    "ANN205",
    "ANN206",
    "ANN003",
    "RET504",
    "RUF001",
    "RUF002",
    "I001",
    "D400",
    "D415",
    "ERA001",
    "S101",
    "W291",
    "Q000",
    "BLE001",
    "N806",
    "FBT003",
    "D102",
    "PGH003",
]

# 可选配置（提升体验）
target-version = "py311"  # 适配你的Python版本
line-length = 88  # 代码行最大长度（符合PEP8）
select = ["ALL"]  # 启用所有规则（除了ignore里的）
